version: '3.4'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --livereload --watch --force_polling --incremental
    volumes:
      - .:/srv/jekyll
    ports:
      - 40000:4000